"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.isBios = exports.findCoreBioses = exports.getPlatforms = exports.defaultPathToData = exports.defaultBiosesUrls = exports.platforms = exports.EmulatorJS = void 0;
var EmulatorJS_1 = require("./EmulatorJS");
Object.defineProperty(exports, "EmulatorJS", { enumerable: true, get: function () { return EmulatorJS_1.EmulatorJS; } });
var platforms_1 = require("./platforms");
Object.defineProperty(exports, "platforms", { enumerable: true, get: function () { return platforms_1.platforms; } });
var defaultBiosesUrls_1 = require("./defaultBiosesUrls");
Object.defineProperty(exports, "defaultBiosesUrls", { enumerable: true, get: function () { return defaultBiosesUrls_1.defaultBiosesUrls; } });
var defaultPathToData_1 = require("./defaultPathToData");
Object.defineProperty(exports, "defaultPathToData", { enumerable: true, get: function () { return defaultPathToData_1.defaultPathToData; } });
var utils_1 = require("./utils");
Object.defineProperty(exports, "getPlatforms", { enumerable: true, get: function () { return utils_1.getPlatforms; } });
Object.defineProperty(exports, "findCoreBioses", { enumerable: true, get: function () { return utils_1.findCoreBioses; } });
Object.defineProperty(exports, "isBios", { enumerable: true, get: function () { return utils_1.isBios; } });
