export const platforms = {
  "3DO": ["opera"],
  Arcade: ["fbneo", "fbalpha2012_cps1", "fbalpha2012_cps2"],
  "Atari 2600": ["stella2014"],
  "Atari 5200": ["a5200"],
  "Atari 7800": ["prosystem"],
  "Atari Jaguar": ["virtualjaguar"],
  "Atari Lynx": ["handy"],
  "MAME 2003": ["mame2003"],
  "NES / Famicom": ["fceumm", "nestopia"],
  "Nintendo 64": ["mupen64plus_next"],
  "Nintendo DS": ["melonds", "desmume2015"],
  "Nintendo GameBoy Advance": ["mgba"],
  "Nintendo GameBoy": ["gambatte", "mgba"],
  PlayStation: ["mednafen_psx", "pcsx_rearmed"],
  "Sega 32X": ["picodrive"],
  "Sega CD": ["genesis_plus_gx", "picodrive"],
  "Sega Game Gear": ["genesis_plus_gx"],
  "Sega Master System": ["genesis_plus_gx", "picodrive"],
  "Sega Mega Drive": ["genesis_plus_gx", "picodrive"],
  "Sega Saturn": ["yabause"],
  SNES: ["snes9x"],
  "Virtual Boy": ["beetle_vb"],
} as const
